### ISSUE TITLE
[JENKINS-71717] plugin is too slow on NFS

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/branch-api-plugin#777]
<p>We have found a thread that is locked is this:</p>

<p><font color="#d1d2d3">Computer.threadPoolForRemoting [</font><font color="#d1d2d3">#494987</font><font color="#d1d2d3">] / waiting for EC2 (DevSecOps Agent) - Linux (i-0b99db4829aeb5474) id=156631640" #13983096 daemon prio=5 os_prio=0 cpu=24150.51ms elapsed=8857.08s tid=0x00007f79d450c800 nid=0x2d447a in Object.wait()  <span class="error">&#91;0x00007f794d4b2000&#93;</span></font><br/>
<font color="#d1d2d3">   java.lang.Thread.State: TIMED_WAITING (on object monitor)</font><br/>
<font color="#d1d2d3">        at java.lang.Object.wait(<span class="nobr"><a href="mailto:java.base@​11.0.18" class="external-link" target="_blank" rel="nofollow noopener">java.base@​11.0.18<sup><img class="rendericon" src="https://issues.jenkins.io/images/icons/mail_small.gif" height="12" width="13" align="absmiddle" alt="" border="0"/></sup></a></span>/Native Method)</font><br/>
<font color="#d1d2d3">        - waiting on <no object reference available></font><br/>
<font color="#d1d2d3">        at hudson.remoting.Request.call(Request.java:177)</font><br/>
<font color="#d1d2d3">        - waiting to re-lock in wait() <0x00000007aee98d98> (a hudson.remoting.UserRequest)</font><br/>
<font color="#d1d2d3">        at hudson.remoting.Channel.call(Channel.java:999)</font><br/>
<font color="#d1d2d3">        at hudson.FilePath.act(FilePath.java:1194)</font><br/>
<font color="#d1d2d3">        at hudson.FilePath.list(FilePath.java:2063)</font><br/>
<font color="#d1d2d3">        at hudson.FilePath.listDirectories(FilePath.java:2037)</font><br/>
<font color="#d1d2d3">        at jenkins.branch.WorkspaceLocatorImpl$Collector.onOnline(WorkspaceLocatorImpl.java:612)</font><br/>
<font color="#d1d2d3">        - locked <0x000000060d199a70> (a java.lang.String)</font><br/>
<font color="#d1d2d3">        at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:748)</font></p>

<p>We don't know for sure why EC2s agent doesn't like this:<br/>
<font color="#d1d2d3">waiting for EC2 (DevSecOps Agent)</font></p>

<p>but we do know it is fine on local storage, but not NFS.</p>

<p>What is interesting is this: <span class="image-wrap" style=""><a id="60892_thumb" href="https://issues.jenkins.io/secure/attachment/60892/60892_image001.png" title="image001.png" file-preview-type="image" file-preview-id="60892" file-preview-title="image001.png"><img src="https://issues.jenkins.io/secure/thumbnail/60892/_thumb_60892.png" style="border: 0px solid black" role="presentation"/></a></span></p>

<p> </p>

<p>Perhaps this could be refactored in order to deal with a large amount of directories on NFS?</p>

---
<details><summary><i>Originally reported by <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/douglasawh.png" title="douglasawh's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=douglasawh">douglasawh</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-71717" target="_blank">plugin is too slow on NFS</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>component(s)</b>: branch-api-plugin
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 3
<li><b>watchers</b>: 1
<li><b>imported</b>: 20251211-141027
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>We have found a thread that is locked is this:</p>

<p><font color="#d1d2d3">Computer.threadPoolForRemoting [</font><font color="#d1d2d3">#494987</font><font color="#d1d2d3">] / waiting for EC2 (DevSecOps Agent) - Linux (i-0b99db4829aeb5474) id=156631640" #13983096 daemon prio=5 os_prio=0 cpu=24150.51ms elapsed=8857.08s tid=0x00007f79d450c800 nid=0x2d447a in Object.wait()  <span class="error">&#91;0x00007f794d4b2000&#93;</span></font>
<font color="#d1d2d3">   java.lang.Thread.State: TIMED_WAITING (on object monitor)</font>
<font color="#d1d2d3">        at java.lang.Object.wait(<span class="nobr"><a href="mailto:java.base@11.0.18" class="external-link" target="_blank" rel="nofollow noopener">java.base@11.0.18<sup><img class="rendericon" src="https://issues.jenkins.io/images/icons/mail_small.gif" height="12" width="13" align="absmiddle" alt="" border="0"/></sup></a></span>/Native Method)</font>
<font color="#d1d2d3">        - waiting on &lt;no object reference available&gt;</font>
<font color="#d1d2d3">        at hudson.remoting.Request.call(Request.java:177)</font>
<font color="#d1d2d3">        - waiting to re-lock in wait() &lt;0x00000007aee98d98&gt; (a hudson.remoting.UserRequest)</font>
<font color="#d1d2d3">        at hudson.remoting.Channel.call(Channel.java:999)</font>
<font color="#d1d2d3">        at hudson.FilePath.act(FilePath.java:1194)</font>
<font color="#d1d2d3">        at hudson.FilePath.list(FilePath.java:2063)</font>
<font color="#d1d2d3">        at hudson.FilePath.listDirectories(FilePath.java:2037)</font>
<font color="#d1d2d3">        at jenkins.branch.WorkspaceLocatorImpl$Collector.onOnline(WorkspaceLocatorImpl.java:612)</font>
<font color="#d1d2d3">        - locked &lt;0x000000060d199a70&gt; (a java.lang.String)</font>
<font color="#d1d2d3">        at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:748)</font></p>

<p>We don't know for sure why EC2s agent doesn't like this:
<font color="#d1d2d3">waiting for EC2 (DevSecOps Agent)</font></p>

<p>but we do know it is fine on local storage, but not NFS.</p>

<p>What is interesting is this: <span class="image-wrap" style=""><a id="60892_thumb" href="https://issues.jenkins.io/secure/attachment/60892/60892_image001.png" title="image001.png" file-preview-type="image" file-preview-id="60892" file-preview-title="image001.png"><img src="https://issues.jenkins.io/secure/thumbnail/60892/_thumb_60892.png" style="border: 0px solid black" role="presentation"/></a></span></p>

<p> </p>

<p>Perhaps this could be refactored in order to deal with a large amount of directories on NFS?</p></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
Jenkins 2.346.2<br/>
Branch API Plugin 2.1046.v0
```
</details>
<details><summary><i>2 attachments</i></summary>

- [image001.png](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-last/refs/heads/main/attachments/60892/image001.png)
  > ![image001.png](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-last/refs/heads/main/attachments/60892/image001.png)
- [image002.png](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-last/refs/heads/main/attachments/60893/image002.png)
  > ![image002.png](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-last/refs/heads/main/attachments/60893/image002.png)
</details>

**Comment by douglasawh** [comment]
This still appears to be an issue. Is there any chance someone can look at this?
